### ISSUE TITLE
invalid value of field `formatters.up_formatter_parameter'

### ISSUE THREAD

**Issue by jeroenf1** [Seeed-Solution/TTN-Payload-Decoder#3]
I try to use the Payload javascript at the TTN Stack (V3) but I receive an error because the maximum allowed size is 4096 bytes. Can you update the Payload-Decoder script for the TTN V3 platform?

**Comment by jeroenf1** [comment]
{
  "code": 3,
  "message": "error:pkg/applicationserver:field_value (invalid value of field `formatters.up_formatter_parameter`)",
  "details": [
    {
      "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
      "namespace": "pkg/applicationserver",
      "name": "field_value",
      "message_format": "invalid value of field `{field}`",
      "attributes": {
        "field": "formatters.up_formatter_parameter"
      },
      "correlation_id": "fd79651a8b2a474587b2954c453f4dce",
      "cause": {
        "namespace": "pkg/applicationserver",
        "name": "formatter_script_too_large",
        "message_format": "formatter script size exceeds maximum allowed size",
        "attributes": {
          "max_size": 4096,
          "size": 10601
        },
        "code": 3
      },
      "code": 3
    }
  ],
  "request_details": {
    "url": "/as/applications/etiming-thialf-sensors/devices/xxxx",
    "method": "put",
    "stack_component": "as"
  }
}

**Comment by jancee** [comment]
Please refer to the commit: https://github.com/Seeed-Solution/TTN-Payload-Decoder/commit/60bbb2fb97aafa131a7efeed1e7e7c4012f7c6cf

Try to use this instead of Decoder.js:
https://github.com/Seeed-Solution/TTN-Payload-Decoder/blob/master/decoder_new-v3-uglifyjs.js

**Comment by jeroenf1** [comment]
![sencap_payloadV3](https://user-images.githubusercontent.com/77023375/123080078-d86b1000-d41c-11eb-8973-6f48d5eca19b.jpg)
I add this script (decoder_new-v3-uglifyjs.js) to the Payload

**Comment by jeroenf1** [comment]
![PayloadSCP](https://user-images.githubusercontent.com/77023375/123093617-30f5d980-d42c-11eb-9df5-660f5a2a36f7.jpg)
Thanks for the script. One small question: I try to find out what the option is to get the air pressure data in the data output. Most sensors gives me the data in the decoder_payload data output. 

{
  "Payload": "010510B0D41506FF3C",
  "err": 0,
  "messages": [
    {
      "measurementId": 4101,
      "measurementValue": 102094, -> 1020.94 hPA
      "type": "report_telemetry"
    }
  ],
  "valid": true
}

I try to add the sensor data in DataCake.

**Comment by jancee** [comment]
If ur using DataCake, u can add a new device, by selecting "New Product from Template", and adding a "SenseCAP" template, with a preset script.

**Comment by jeroenf1** [comment]
Yes, I choose the SenseCap Baromatic sensor but the Payload decoder is not prepared for Air pressure values:

function Decoder(bytes, port) {
  var decoded = {};
 
  var battery = -99;
  var interval = -99;
  var temp = -99;
  var hum = -99;
  var ch1 = -99;
  var ch2 = -99;
  var ch3 = -99;
  var val01 = -99;
  var val02 = -99;
  var val03 = -99;
   
  ch01 = bytes[0];
 
  val01 = ((bytes[2] << 8) | bytes[1]);
 
  if (val01 === 7) { // battery
    battery = (bytes[4] << 8) | bytes[3];
    interval = (bytes[6] << 8) | bytes[5];
  }
 
  if (val01 === 4097) // temperature
    temp = ((bytes[6] << 24) | (bytes[5] << 16) | (bytes[4] << 8) | bytes[3]) /1000 ;
 
  ch02 = bytes[7];
 
  val02 = ((bytes[9] << 8) | bytes[8]);
 
  if (val02 === 4097) // temperature
    temp = ((bytes[13] << 24) | (bytes[12] << 16) | (bytes[11] << 8) | bytes[10]) /1000 ;
 
  if (val02 === 4098)
    hum = ((bytes[13] << 24) | (bytes[12] << 16) | (bytes[11] << 8) | bytes[10]) / 1000;
 
  ch03 = bytes[14];
 
  val03 = ((bytes[16] << 8) | bytes[15]);
 
  if (val03 === 4097) // temperature
    temp = ((bytes[20] << 24) | (bytes[19] << 16) | (bytes[18] << 8) | bytes[17]) /1000 ;
 
  if (val03 === 4098)
    hum = ((bytes[20] << 24) | (bytes[19] << 16) | (bytes[18] << 8) | bytes[17]) / 1000;
 
  decoded.ch01 = ch01;
  decoded.val01 = val01;
  decoded.ch02 = ch02;
  decoded.val02 = val02;
  decoded.ch03 = ch03;
  decoded.val03 = val03;
  decoded.battery = battery;
  decoded.interval = interval;
  decoded.temperature = temp;
  decoded.humidity = hum;
 
  return decoded;
}

**Comment by jancee** [comment]
refer, https://github.com/Seeed-Solution/TTN-Payload-Decoder/blob/master/datacake/decoder.js
